{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: {{ template "preprocessingcontroller.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "preprocessingcontroller.fullname" . }}
rules:
  - apiGroups: ["", "apps"]
    resources:
      - endpoints
      - deployments
      - configmaps
      - pods
      - services
      - secrets
      - serviceaccounts
      - replicasets
    verbs:
      - get
      - create
      - delete
      - patch
      - update
  {{- end -}}